import {chromium} from 'playwright';
const baseURL=process.argv[2]||process.env.CYBERLARVA_URL||'http://127.0.0.1:8775';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto(baseURL);
await page.waitForFunction(()=>window.cyberLarvaReady,null,{timeout:60000});
await page.locator('#play').click();
await page.waitForFunction(()=>parseFloat(document.getElementById('simtime').textContent)>.5,null,{timeout:60000});
await page.locator('#play').click();await page.waitForTimeout(1200);
await page.locator('#lesion').click();await page.locator('#neuronsearch').fill('DN-VNC');await page.waitForTimeout(500);const neuronChoices=await page.locator('.neuron').count();if(neuronChoices){await page.locator('.neuron').first().click();await page.waitForTimeout(250)}const knockoutCount=await page.evaluate(async()=>(await(await fetch('/api/state')).json()).knockout.count);await page.locator('#clearKO').click();await page.waitForTimeout(200);
await page.screenshot({path:'preview.png'});
await page.locator('#macro').click();await page.waitForTimeout(700);await page.screenshot({path:'preview-macro.png'});
await page.locator('#overview').click();await page.waitForTimeout(700);const overview=await page.evaluate(()=>structuredClone(window.cyberLarvaView));await page.mouse.move(520,460);await page.mouse.down();await page.mouse.move(650,410,{steps:8});await page.mouse.up();await page.waitForTimeout(500);const overviewRotated=await page.evaluate(()=>structuredClone(window.cyberLarvaView));await page.screenshot({path:'preview-overview.png'});
const report=await page.evaluate(async()=>({ready:window.cyberLarvaReady,status:document.getElementById('status').textContent,source:document.getElementById('source').textContent,active:document.getElementById('active').textContent,fps:document.getElementById('fps').textContent,state:await(await fetch('/api/state')).json()}));
await page.locator('#editor').click();await page.waitForTimeout(500);const edited=await page.evaluate(async()=>{let before=await(await fetch('/api/world')).json();await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'paint',tool:'fungus',x:3,y:3})});let after=await(await fetch('/api/world')).json();return after.revision>before.revision&&after.items.some(x=>x.kind==='fungus'&&x.x===3.5)});
const orbitMoved=overview.position.some((v,i)=>Math.abs(v-overviewRotated.position[i])>.01);
console.log(JSON.stringify({ready:report.ready,status:report.status,source:report.source,active:report.active,fps:report.fps,segments:report.state.segments.length,neuronChoices,knockoutCount,overview,orbitMoved,edited,errors},null,2));
await browser.close();if(errors.length||!edited||report.state.segments.length!==11||!neuronChoices||knockoutCount!==1||overview.mode!=='overview'||Math.abs(overview.target[0]-12)>.01||Math.abs(overview.target[2]-10)>.01||!orbitMoved)process.exitCode=1;
