import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';

const $=id=>document.getElementById(id), renderer=new T.WebGLRenderer({antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;$('viewport').appendChild(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#182219');scene.fog=new T.FogExp2('#19231a',.025);
const camera=new T.PerspectiveCamera(38,innerWidth/innerHeight,.025,120),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.7;controls.maxDistance=42;controls.maxPolarAngle=Math.PI*.49;
const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;pmrem.dispose();scene.environmentIntensity=.62;
scene.add(new T.HemisphereLight('#dae7c4','#28311f',1.1));const sun=new T.DirectionalLight('#fff0bf',3);sun.position.set(-7,15,4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-16,right:16,top:16,bottom:-16,near:.3,far:40});scene.add(sun);scene.add(sun.target);
const habitat=new T.Group(),larva=new T.Group(),items=new T.Group();scene.add(habitat,items,larva);
const mats={agar:new T.MeshPhysicalMaterial({color:'#736e51',roughness:.73,clearcoat:.2}),rim:new T.MeshPhysicalMaterial({color:'#81948a',roughness:.12,transmission:.4,transparent:true,opacity:.45,side:T.DoubleSide}),
 stone:new T.MeshStandardMaterial({color:'#777b68',roughness:.9}),leaf:new T.MeshStandardMaterial({color:'#48683c',roughness:.68,side:T.DoubleSide}),vein:new T.MeshStandardMaterial({color:'#9baa62',roughness:.7}),food:new T.MeshPhysicalMaterial({color:'#bb7842',roughness:.52,clearcoat:.16}),fungus:new T.MeshStandardMaterial({color:'#d8c5a2',roughness:.82}),water:new T.MeshPhysicalMaterial({color:'#355c59',roughness:.08,metalness:.15,transparent:true,opacity:.7,clearcoat:1}),wall:new T.MeshStandardMaterial({color:'#626858',roughness:.9}),
 skin:new T.MeshPhysicalMaterial({color:'#ffffff',roughness:.38,transmission:.20,transparent:true,opacity:.60,clearcoat:.14,clearcoatRoughness:.36,thickness:.38,ior:1.35,attenuationColor:'#f1eee9',attenuationDistance:2.4,vertexColors:true,side:T.DoubleSide,depthWrite:false}),skinHead:new T.MeshPhysicalMaterial({color:'#f0ede8',roughness:.42,transmission:.18,transparent:true,opacity:.58,clearcoat:.12,depthWrite:false}),mouth:new T.MeshPhysicalMaterial({color:'#312d29',roughness:.50,transparent:true,opacity:.72}),spiracle:new T.MeshStandardMaterial({color:'#91877f',roughness:.66}),gut:new T.MeshPhysicalMaterial({color:'#9f958d',roughness:.55,transparent:true,opacity:.20,depthWrite:false}),nerve:new T.MeshStandardMaterial({color:'#b7db6b',emissive:'#78b349',emissiveIntensity:1.2,roughness:.5}),brain:new T.MeshPhysicalMaterial({color:'#d7e875',emissive:'#8aa83e',emissiveIntensity:1.2,transparent:true,opacity:.65})};
function mesh(g,m,p,pos=[0,0,0],sc=[1,1,1]){const o=new T.Mesh(g,m);o.position.set(...pos);o.scale.set(...sc);o.castShadow=true;o.receiveShadow=true;p.add(o);return o}function clear(g){while(g.children.length){let o=g.children[0];g.remove(o);o.traverse(x=>{if(x.isMesh)x.geometry.dispose()})}}
let seed=11;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
function texture(){let c=document.createElement('canvas');c.width=c.height=512;let x=c.getContext('2d');x.fillStyle='#746f51';x.fillRect(0,0,512,512);seed=31;for(let i=0;i<19000;i++){let q=rand()*1.7;x.fillStyle=`rgba(${rand()>.5?'225,210,156':'34,39,24'},${rand()*.16})`;x.fillRect(rand()*512,rand()*512,q,q)}let t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(9,8);t.colorSpace=T.SRGBColorSpace;return t}mats.agar.map=texture();mats.agar.bumpMap=mats.agar.map;mats.agar.bumpScale=.035;
function leaf(it){let g=new T.Group();g.position.set(it.x,.02,it.y);g.rotation.y=it.x*.7;items.add(g);let shape=new T.Shape();shape.moveTo(0,0);shape.bezierCurveTo(-.6,.25,-.7,1.1,0,1.5);shape.bezierCurveTo(.7,1.1,.6,.25,0,0);let l=mesh(new T.ShapeGeometry(shape,16),mats.leaf,g);l.rotation.x=-Math.PI/2;l.rotation.z=-.15;l.scale.set(it.radius,it.radius,it.radius);let v=mesh(new T.CylinderGeometry(.012,.018,1.35,7),mats.vein,g,[0,.018,.7]);v.rotation.x=Math.PI/2}
function buildItem(it){if(it.kind==='leaf')return leaf(it);if(it.kind==='food'){let g=new T.Group();g.position.set(it.x,.06,it.y);items.add(g);for(let i=0;i<7;i++){let p=mesh(new T.SphereGeometry(.17,16,10),mats.food,g,[Math.cos(i*.9)*.22,Math.sin(i*1.2)*.035,Math.sin(i*.9)*.22],[1,.45,1]);p.rotation.y=i}return}if(it.kind==='rock'){let r=mesh(new T.IcosahedronGeometry(1,2),mats.stone,items,[it.x,it.radius*.42,it.y],[it.radius,it.radius*.65,it.radius*.85]);r.rotation.set(.2,it.x,.1);return}if(it.kind==='puddle'){let p=mesh(new T.CircleGeometry(it.radius,48),mats.water,items,[it.x,.008,it.y],[1,.82,1]);p.rotation.x=-Math.PI/2;p.castShadow=false;return}if(it.kind==='fungus'){let g=new T.Group();g.position.set(it.x,0,it.y);items.add(g);for(let i=0;i<5;i++){let a=i*2.4,r=i*.11;mesh(new T.CylinderGeometry(.035,.055,.35+i*.035,8),mats.fungus,g,[Math.cos(a)*r,.18,Math.sin(a)*r]);mesh(new T.SphereGeometry(.13,12,8,0,Math.PI*2,0,Math.PI/2),mats.fungus,g,[Math.cos(a)*r,.36+i*.035,Math.sin(a)*r],[1,.55,1])}}}
let mapData,lastRevision=-1;function buildWorld(d){mapData=d;lastRevision=d.revision;clear(habitat);clear(items);let w=d.grid[0].length,h=d.grid.length;let floor=mesh(new T.BoxGeometry(w,.35,h),mats.agar,habitat,[w/2,-.2,h/2]);floor.castShadow=false;mesh(new T.CylinderGeometry(Math.max(w,h)*.76,Math.max(w,h)*.76,.33,96,1,true),mats.rim,habitat,[w/2,.02,h/2]).rotation.x=Math.PI/2;
 seed=91;let peb=new T.InstancedMesh(new T.IcosahedronGeometry(1,1),mats.stone,600),m=new T.Matrix4(),q=new T.Quaternion(),s=new T.Vector3();for(let i=0;i<600;i++){let r=.015+rand()*.045;m.compose(new T.Vector3(1+rand()*(w-2),.005,1+rand()*(h-2)),q.setFromAxisAngle(new T.Vector3(0,1,0),rand()*6),s.set(r,r*.55,r));peb.setMatrixAt(i,m)}habitat.add(peb);
 for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(d.grid[y][x]==='#'&&x>0&&y>0&&x<w-1&&y<h-1){let r=mesh(new T.DodecahedronGeometry(.5,0),mats.wall,habitat,[x+.5,.28,y+.5],[1,.65,1]);r.rotation.y=rand()*4}d.items.forEach(buildItem)}

const segMeshes=[],muscleRings=[],neuralGroup=new T.Group(),sphereGeo=new T.SphereGeometry(1,36,24),ringGeo=new T.TorusGeometry(1,.008,7,40);larva.add(neuralGroup);neuralGroup.visible=false;const denticleCount=49,denticleGeo=new T.ConeGeometry(.0028,.005,5),denticleMat=new T.MeshStandardMaterial({color:'#8d837b',roughness:.78,transparent:true,opacity:.34}),denticleMesh=new T.InstancedMesh(denticleGeo,denticleMat,denticleCount);denticleMesh.castShadow=false;larva.add(denticleMesh);
for(let i=0;i<11;i++){let anchor=new T.Object3D();larva.add(anchor);segMeshes.push(anchor);let ring=mesh(ringGeo,new T.MeshPhysicalMaterial({color:'#b98e72',roughness:.34,transparent:true,opacity:.12}),larva);muscleRings.push(ring)}
// Radius profile traced from the user-provided D. melanogaster panel: narrow
// anterior, broad middle, gently tapered blunt posterior.
// SEM dorsal/ventral/lateral outline: nearly parallel-sided trunk, short
// pseudocephalon transition, and a compact taper into the anal segment.
const larvaProfile=[.045,.085,.125,.142,.147,.150,.151,.151,.150,.149,.148,.147,.146,.145,.143,.140,.136,.131,.123,.110,.090];
function profileRadius(t){let x=t*(larvaProfile.length-1),i=Math.min(larvaProfile.length-2,Math.floor(x)),f=x-i;return T.MathUtils.lerp(larvaProfile[i],larvaProfile[i+1],f)}
const skinSides=32,skinRings=41,skinRingVertices=skinRings*skinSides,skinPos=new Float32Array((skinRingVertices+2)*3),skinColors=new Float32Array((skinRingVertices+2)*3),skinIndex=[];
for(let i=0;i<skinRings-1;i++)for(let j=0;j<skinSides;j++){let a=i*skinSides+j,b=i*skinSides+(j+1)%skinSides,c=(i+1)*skinSides+j,d=(i+1)*skinSides+(j+1)%skinSides;skinIndex.push(a,c,b,b,c,d)}
const headTone=new T.Color('#ddd9d3'),midTone=new T.Color('#faf8f4'),tailTone=new T.Color('#ebe8e2');for(let i=0;i<skinRings;i++){let t=i/(skinRings-1),c=t<.24?new T.Color().lerpColors(headTone,midTone,t/.24):new T.Color().lerpColors(midTone,tailTone,(t-.24)/.76);for(let j=0;j<skinSides;j++){let k=(i*skinSides+j)*3,light=.97+.03*Math.sin(j/skinSides*Math.PI);skinColors[k]=c.r*light;skinColors[k+1]=c.g*light;skinColors[k+2]=c.b*light}}
const headCenter=skinRingVertices,tailCenter=skinRingVertices+1;for(let j=0;j<skinSides;j++){skinIndex.push(headCenter,(j+1)%skinSides,j);let a=(skinRings-1)*skinSides+j,b=(skinRings-1)*skinSides+(j+1)%skinSides;skinIndex.push(tailCenter,a,b)}for(let [i,c] of [[headCenter,headTone],[tailCenter,tailTone]]){skinColors[i*3]=c.r;skinColors[i*3+1]=c.g;skinColors[i*3+2]=c.b}
const skinGeo=new T.BufferGeometry();skinGeo.setAttribute('position',new T.BufferAttribute(skinPos,3));skinGeo.setAttribute('color',new T.BufferAttribute(skinColors,3));skinGeo.setIndex(skinIndex);const skinBody=mesh(skinGeo,mats.skin,larva);skinBody.frustumCulled=false;
// A subdued translucent gut adds biological depth without obscuring the CNS.
const gutSides=12,gutRings=25,gutPos=new Float32Array(gutRings*gutSides*3),gutIndex=[];for(let i=0;i<gutRings-1;i++)for(let j=0;j<gutSides;j++){let a=i*gutSides+j,b=i*gutSides+(j+1)%gutSides,c=(i+1)*gutSides+j,d=(i+1)*gutSides+(j+1)%gutSides;gutIndex.push(a,c,b,b,c,d)}const gutGeo=new T.BufferGeometry();gutGeo.setAttribute('position',new T.BufferAttribute(gutPos,3));gutGeo.setIndex(gutIndex);const gutBody=mesh(gutGeo,mats.gut,larva);gutBody.frustumCulled=false;
// The cephalopharyngeal skeleton and mouth hooks remain inside the transparent head.
const mouth=new T.Group();larva.add(mouth);const oralPlate=mesh(new T.SphereGeometry(1,18,12),mats.mouth,mouth,[-.007,-.001,0],[.017,.011,.015]);for(let side of [-1,1]){let curve=new T.CatmullRomCurve3([new T.Vector3(-.004,side*.005,-.003),new T.Vector3(-.018,side*.010,-.003),new T.Vector3(-.036,side*.012,.002),new T.Vector3(-.055,side*.008,.007)]);mesh(new T.TubeGeometry(curve,14,.004,7,false),mats.mouth,mouth)}let pharynx=mesh(new T.CapsuleGeometry(.007,.034,5,10),mats.mouth,mouth,[-.038,.009,0],[.7,.7,.7]);pharynx.rotation.z=Math.PI/2;
const posterior=new T.Group();larva.add(posterior);for(let side of [-1,1]){mesh(new T.CylinderGeometry(.008,.011,.025,10),mats.spiracle,posterior,[0,0,side*.028]).rotation.z=Math.PI/2;mesh(new T.SphereGeometry(.011,10,7),mats.spiracle,posterior,[.012,0,side*.028])}
const brainL=mesh(sphereGeo,mats.brain,neuralGroup,[0,0,0],[.024,.016,.019]),brainR=mesh(sphereGeo,mats.brain,neuralGroup,[0,0,0],[.024,.016,.019]);mats.brain.depthTest=true;mats.nerve.depthTest=true;
const nerveNodes=[];for(let i=0;i<11;i++)nerveNodes.push(mesh(sphereGeo,mats.nerve,neuralGroup,[0,0,0],[.017,.012,.012]));let nerveLine=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:'#badd6d',transparent:true,opacity:.72,depthTest:false}));neuralGroup.add(nerveLine);
let latest,follow=true,editing=false,selected='food',pathLine;const pathMat=new T.LineBasicMaterial({color:'#a4c568',transparent:true,opacity:.5});
async function cmd(d){let r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}),j=await r.json();if(!r.ok)throw Error(j.error);return j}function toast(t){$('toast').textContent=t;$('toast').style.opacity=1;clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').style.opacity=0,2800)}
async function poll(){try{latest=await(await fetch('/api/state')).json();if(latest.revision!==lastRevision)buildWorld(await(await fetch('/api/world')).json());
 const names={'resting':'静止','forward crawling':'前向蠕动','backward escape':'后退逃逸','head casting':'头部扫描','feeding':'进食'},p=latest.physics||{},target=p.targets||{};$('behavior').textContent=names[latest.behavior]||latest.behavior;$('simtime').textContent=latest.time.toFixed(2)+' s';$('source').textContent=latest.stats.source||'正在初始化';$('engine').textContent=p.engine||'MuJoCo';$('active').textContent=(latest.stats.active??0).toLocaleString();$('knockout').textContent=(latest.knockout?.count||0)+' 个';$('stepms').textContent=latest.stats.step_ms?(latest.stats.step_ms.toFixed(1)+' / '+(latest.stats.physics_ms||0).toFixed(1)+' ms'):'—';$('speed').textContent=p.speed_bl_s!=null?p.speed_bl_s.toFixed(2)+' / '+target.speed_bl_s.toFixed(2)+' BL/s':'—';$('curvature').textContent=p.curvature_rad_bl!=null?p.curvature_rad_bl.toFixed(2)+' / '+target.curvature_rad_bl.toFixed(2):'—';$('contacts').textContent=p.contact_count??'—';$('food').textContent=latest.foods_found;$('status').textContent=latest.error?latest.error:(latest.paused?'模拟已暂停':'神经—肌肉—接触闭环运行中');$('play').textContent=latest.paused?'开始探索':'暂停探索';
 for(let [k,id] of [['forward','forward'],['backward','back']]){let v=latest.stats[k]||0;$(id+'bar').style.width=v*100+'%';$(id+'v').textContent=Math.round(v*100)+'%'}let tv=latest.stats.turn||0;$('turnv').textContent=(tv>=0?'+':'')+tv.toFixed(2);$('turnbar').style.left=(tv<0?50+tv*50:50)+'%';$('turnbar').style.width=Math.abs(tv)*50+'%';$('turnbar').style.background=tv<0?'#7bb1b0':'#d0d87b';
 if(pathLine){scene.remove(pathLine);pathLine.geometry.dispose()}pathLine=new T.Line(new T.BufferGeometry().setFromPoints(latest.trail.map(p=>new T.Vector3(p[0],.025,p[1]))),pathMat);pathLine.visible=$('trail').checked;scene.add(pathLine);
 }catch(e){$('status').textContent='本地服务连接中断'}setTimeout(poll,100)}
buildWorld(await(await fetch('/api/world')).json());latest=await(await fetch('/api/state')).json();camera.position.set(14,3.2,13);controls.target.set(11.4,.2,9.4);controls.update();poll();setTimeout(()=>view('follow'),350);
function view(v){let target=v==='overview'?segMeshes[0].position.clone():segMeshes[v==='macro'?3:4].position.clone(),off=v==='macro'?new T.Vector3(1.6,.7,1.35):v==='overview'?new T.Vector3(12,18,12):new T.Vector3(2.25,1.25,2.05);controls.target.copy(target);camera.position.copy(target).add(off);follow=v!=='overview';for(let k of ['follow','macro','overview'])$(k).classList.toggle('selected',k===v)}for(let k of ['follow','macro','overview'])$(k).onclick=()=>view(k);
$('play').onclick=()=>cmd({action:'pause',value:!latest.paused});$('reset').onclick=()=>cmd({action:'reset'});$('neural').onchange=()=>neuralGroup.visible=$('neural').checked;$('trail').onchange=()=>{if(pathLine)pathLine.visible=$('trail').checked};
const tools=[['food','食物'],['leaf','叶片'],['rock','岩石'],['fungus','菌簇'],['puddle','水洼'],['wall','障碍'],['floor','清墙'],['spawn','出生点']];for(let [k,n] of tools){let b=document.createElement('button');b.textContent=n;b.classList.toggle('selected',k===selected);b.onclick=()=>{selected=k;[...$('palette').children].forEach(x=>x.classList.toggle('selected',x===b))};$('palette').appendChild(b)}$('editor').onclick=async()=>{editing=!editing;$('editpanel').hidden=!editing;$('editor').textContent=editing?'完成编辑':'✦ 编辑生态舱';if(editing){await cmd({action:'pause',value:true});view('overview');toast('单击放置，右键擦除')}};for(let a of ['save','load','garden'])$(a).onclick=()=>cmd({action:a}).then(()=>toast({save:'地图已保存',load:'地图已载入',garden:'自然生态舱已复原'}[a])).catch(e=>toast(e.message));
let lesionOpen=false,neuronTimer;async function loadNeurons(){let q=encodeURIComponent($('neuronsearch').value.trim()),data=await(await fetch('/api/neurons?q='+q+'&limit=80')).json(),box=$('neuronresults');box.replaceChildren();for(let n of data.neurons){let b=document.createElement('button'),mark=document.createElement('span'),copy=document.createElement('span'),title=document.createElement('b'),meta=document.createElement('small');b.className='neuron'+(n.disabled?' selected':'');mark.textContent=n.disabled?'✓':'○';title.textContent=(n.id||n.index)+(n.side?' · '+n.side:'');meta.textContent=[n.celltype,n.annotations,n.cluster&&('cluster '+n.cluster)].filter(Boolean).join(' · ')||('connectome index '+n.index);copy.append(title,meta);b.append(mark,copy);b.onclick=async()=>{await cmd({action:'knockout',mode:n.disabled?'remove':'add',indices:[n.index]});await loadNeurons();toast(n.disabled?'神经元已恢复':'神经元已沉默')};box.appendChild(b)}$('kosummary').textContent=data.knockout.count?('已沉默 '+data.knockout.count+' 个神经元'):'尚未沉默神经元'}$('lesion').onclick=()=>{lesionOpen=!lesionOpen;$('lesionpanel').hidden=!lesionOpen;$('lesion').textContent=lesionOpen?'收起沉默实验':'◇ 神经元沉默实验';if(lesionOpen)loadNeurons()};$('neuronsearch').oninput=()=>{clearTimeout(neuronTimer);neuronTimer=setTimeout(loadNeurons,180)};$('clearKO').onclick=async()=>{await cmd({action:'clear_knockout'});await loadNeurons();toast('全部神经元已恢复')};
const cursor=mesh(new T.RingGeometry(.35,.48,24),new T.MeshBasicMaterial({color:'#c7df79',side:T.DoubleSide}),scene);cursor.rotation.x=-Math.PI/2;cursor.visible=false;const ray=new T.Raycaster(),mouse=new T.Vector2(),ground=new T.Plane(new T.Vector3(0,1,0),0),hit=new T.Vector3();let cell,down;renderer.domElement.onpointermove=e=>{if(!editing)return;mouse.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(mouse,camera);if(ray.ray.intersectPlane(ground,hit)){cell={x:Math.floor(hit.x),y:Math.floor(hit.z)};cursor.position.set(cell.x+.5,.025,cell.y+.5);cursor.visible=true}};renderer.domElement.onpointerdown=e=>down=[e.clientX,e.clientY];renderer.domElement.onpointerup=e=>{if(editing&&cell&&down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<5)cmd({action:'paint',...cell,tool:e.button===2?'erase':selected});down=null};renderer.domElement.oncontextmenu=e=>e.preventDefault();
let last=performance.now(),frames=0,fpsTime=last,oldHead=new T.Vector3(),up=new T.Vector3(0,1,0),xAxis=new T.Vector3(1,0,0),zAxis=new T.Vector3(0,0,1);
function animate(now){requestAnimationFrame(animate);let dt=Math.min(.05,(now-last)/1000);last=now;
 if(latest?.segments?.length===11){let pts=[];
  for(let i=0;i<11;i++){let p=latest.segments[i],s=segMeshes[i];s.position.lerp(new T.Vector3(p.x,p.z,p.y),1-Math.exp(-dt*18));nerveNodes[i].position.copy(s.position).add(new T.Vector3(0,.015,0));nerveNodes[i].scale.setScalar(.010+p.muscle*.012);pts.push(nerveNodes[i].position.clone())}
  const curve=new T.CatmullRomCurve3(segMeshes.map(s=>s.position.clone()),false,'centripetal'),point=new T.Vector3(),tangent=new T.Vector3(),side=new T.Vector3();
  // Resample the 11 MuJoCo bodies into a smooth, high-resolution living skin.
  for(let i=0;i<skinRings;i++){let t=i/(skinRings-1),x=t*10,lo=Math.min(9,Math.floor(x)),f=x-lo,m=T.MathUtils.lerp(latest.segments[lo].muscle,latest.segments[lo+1].muscle,f);curve.getPointAt(t,point);curve.getTangentAt(t,tangent);side.set(-tangent.z,0,tangent.x).normalize();let d=x-Math.round(x),groove=Math.exp(-Math.pow(d/.13,2)),shoulder=Math.exp(-Math.pow((Math.abs(d)-.23)/.085,2)),seam=Math.min(t,1-t)>.025?1-.125*groove+.032*shoulder:1,r=profileRadius(t)*(1-m*.06)*seam;for(let j=0;j<skinSides;j++){let a=j/skinSides*Math.PI*2,vertical=Math.sin(a),micro=1+.006*Math.sin(t*163+Math.sin(a*7)*1.7)+.0035*Math.sin(a*17+t*53),height=r*(vertical>0?.80:.62)*micro,lobing=(1+.015*Math.cos(a*2))*micro,v=point.clone().addScaledVector(side,Math.cos(a)*r*lobing).addScaledVector(up,vertical*height+.003*Math.sin(t*Math.PI));let k=(i*skinSides+j)*3;skinPos[k]=v.x;skinPos[k+1]=v.y;skinPos[k+2]=v.z}}
  curve.getPointAt(0,point);curve.getTangentAt(0,tangent).negate();point.addScaledVector(tangent,.038);skinPos[headCenter*3]=point.x;skinPos[headCenter*3+1]=point.y;skinPos[headCenter*3+2]=point.z;curve.getPointAt(1,point);curve.getTangentAt(1,tangent);point.addScaledVector(tangent,.040);skinPos[tailCenter*3]=point.x;skinPos[tailCenter*3+1]=point.y;skinPos[tailCenter*3+2]=point.z;skinGeo.attributes.position.needsUpdate=true;skinGeo.computeVertexNormals();
  // A narrower internal tube makes the translucent body read as biological tissue.
  for(let i=0;i<gutRings;i++){let t=i/(gutRings-1),tt=.055+t*.9;curve.getPointAt(tt,point);curve.getTangentAt(tt,tangent);side.set(-tangent.z,0,tangent.x).normalize();let r=.019+.023*Math.sin(t*Math.PI);for(let j=0;j<gutSides;j++){let a=j/gutSides*Math.PI*2,v=point.clone().addScaledVector(side,Math.cos(a)*r).addScaledVector(up,Math.sin(a)*r*.62-.012),k=(i*gutSides+j)*3;gutPos[k]=v.x;gutPos[k+1]=v.y;gutPos[k+2]=v.z}}gutGeo.attributes.position.needsUpdate=true;gutGeo.computeVertexNormals();
  for(let i=0;i<11;i++){let t=i/10,p=latest.segments[i];curve.getPointAt(t,point);curve.getTangentAt(t,tangent);let ring=muscleRings[i],r=profileRadius(t);ring.position.copy(point);ring.quaternion.setFromUnitVectors(zAxis,tangent);ring.scale.set(r*.995,r*.72,r*.995);ring.material.opacity=.08+p.muscle*.07}
  let di=0,denticleMatrix=new T.Matrix4(),denticleQuat=new T.Quaternion(),denticleScale=new T.Vector3(1,1,1),yAxis=new T.Vector3(0,1,0);for(let band=0;band<7;band++){let t=.24+band*.095;curve.getPointAt(t,point);curve.getTangentAt(t,tangent);side.set(-tangent.z,0,tangent.x).normalize();let r=profileRadius(t);for(let tooth=-3;tooth<=3;tooth++){let lateral=tooth/3*r*.54,pos=point.clone().addScaledVector(side,lateral).addScaledVector(up,-r*.61),normal=up.clone().multiplyScalar(-1).addScaledVector(side,tooth*.07).normalize();denticleQuat.setFromUnitVectors(yAxis,normal);denticleMatrix.compose(pos,denticleQuat,denticleScale);denticleMesh.setMatrixAt(di++,denticleMatrix)}}denticleMesh.instanceMatrix.needsUpdate=true;
  let h=curve.getPointAt(0,new T.Vector3()),forward=curve.getTangentAt(0,new T.Vector3()).negate();mouth.position.copy(h).addScaledVector(forward,.031).add(new T.Vector3(0,-.010,0));mouth.quaternion.setFromUnitVectors(xAxis,forward);let tailDir=curve.getTangentAt(1,new T.Vector3());posterior.position.copy(curve.getPointAt(1,new T.Vector3())).addScaledVector(tailDir,.031);posterior.quaternion.setFromUnitVectors(xAxis,tailDir);
  curve.getTangentAt(.07,tangent);side.set(-tangent.z,0,tangent.x).normalize();let brainCenter=curve.getPointAt(.07,new T.Vector3()).add(new T.Vector3(0,.018,0));brainL.position.copy(brainCenter).addScaledVector(side,.027);brainR.position.copy(brainCenter).addScaledVector(side,-.027);nerveLine.geometry.dispose();nerveLine.geometry=new T.BufferGeometry().setFromPoints(pts);
  if(follow&&!editing){let d=h.clone().sub(oldHead);camera.position.add(d);controls.target.add(d)}oldHead.copy(h);sun.target.position.copy(h);sun.position.copy(h).add(new T.Vector3(-7,15,4))}
 controls.update();renderer.render(scene,camera);frames++;if(now-fpsTime>1000){$('fps').textContent=Math.round(frames*1000/(now-fpsTime))+' FPS';frames=0;fpsTime=now}window.cyberLarvaReady=latest?.segments?.length===11}
requestAnimationFrame(animate);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
